# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rpayload.proto\"\xf5\x01\n\x06Route1\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x1a\n\x04path\x18\x02 \x01(\x0e\x32\x0c.Route1.Path\x12\x39\n\x16networkDiscoveryPacket\x18\x03 \x01(\x0b\x32\x17.NetworkDiscoveryPacketH\x00\x12\x15\n\x04user\x18\x04 \x01(\x0b\x32\x05.UserH\x00\x12\x1b\n\x07message\x18\x05 \x01(\x0b\x32\x08.MessageH\x00\"I\n\x04Path\x12\x08\n\x04PING\x10\x00\x12\x15\n\x11NETWORK_DISCOVERY\x10\x01\x12\x08\n\x04USER\x10\x02\x12\x0b\n\x07MESSAGE\x10\x03\x12\t\n\x05GROUP\x10\x04\x42\t\n\x07payload\"\xc7\x01\n\x07Message\x12\x1b\n\x04type\x18\x01 \x02(\x0e\x32\r.Message.Type\x12\x0e\n\x06sender\x18\x02 \x02(\t\x12\x0f\n\x07payload\x18\x03 \x02(\t\x12\n\n\x02to\x18\x04 \x02(\t\x12\x11\n\ttimestamp\x18\x05 \x02(\t\x12\x1f\n\x06status\x18\x06 \x02(\x0e\x32\x0f.Message.Status\"\x1d\n\x04Type\x12\n\n\x06SINGLE\x10\x00\x12\t\n\x05GROUP\x10\x01\"\x1f\n\x06Status\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\t\n\x05STALE\x10\x01\"A\n\x04User\x12\r\n\x05\x65mail\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x18\n\x10recentActiveTime\x18\x03 \x01(\t\"\xe1\x02\n\x16NetworkDiscoveryPacket\x12*\n\x04mode\x18\x01 \x02(\x0e\x32\x1c.NetworkDiscoveryPacket.Mode\x12;\n\x06sender\x18\x02 \x02(\x0e\x32\x1e.NetworkDiscoveryPacket.Sender:\x0bSERVER_NODE\x12\x10\n\x08groupTag\x18\x03 \x01(\t\x12\x0e\n\x06nodeId\x18\x04 \x01(\t\x12\x13\n\x0bnodeAddress\x18\x05 \x02(\t\x12\x10\n\x08nodePort\x18\x06 \x02(\t\x12\x0e\n\x06secret\x18\x07 \x02(\t\"b\n\x06Sender\x12\x18\n\x14\x45XTERNAL_SERVER_NODE\x10\x00\x12\x18\n\x14INTERNAL_SERVER_NODE\x10\x01\x12\x13\n\x0f\x45ND_USER_CLIENT\x10\x02\x12\x0f\n\x0bSERVER_NODE\x10\x03\"!\n\x04Mode\x12\x0b\n\x07REQUEST\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x42\x0b\n\x07routingH\x01')
)



_ROUTE1_PATH = _descriptor.EnumDescriptor(
  name='Path',
  full_name='Route1.Path',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NETWORK_DISCOVERY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUP', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_ROUTE1_PATH)

_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Message.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=403,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_TYPE)

_MESSAGE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Message.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STALE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=434,
  serialized_end=465,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_STATUS)

_NETWORKDISCOVERYPACKET_SENDER = _descriptor.EnumDescriptor(
  name='Sender',
  full_name='NetworkDiscoveryPacket.Sender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXTERNAL_SERVER_NODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SERVER_NODE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END_USER_CLIENT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_NODE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=755,
  serialized_end=853,
)
_sym_db.RegisterEnumDescriptor(_NETWORKDISCOVERYPACKET_SENDER)

_NETWORKDISCOVERYPACKET_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='NetworkDiscoveryPacket.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=855,
  serialized_end=888,
)
_sym_db.RegisterEnumDescriptor(_NETWORKDISCOVERYPACKET_MODE)


_ROUTE1 = _descriptor.Descriptor(
  name='Route1',
  full_name='Route1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Route1.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='Route1.path', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='networkDiscoveryPacket', full_name='Route1.networkDiscoveryPacket', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='Route1.user', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='Route1.message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROUTE1_PATH,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='Route1.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=18,
  serialized_end=263,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='Message.sender', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Message.payload', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='Message.to', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Message.timestamp', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Message.status', index=5,
      number=6, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_TYPE,
    _MESSAGE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=465,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='User.email', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recentActiveTime', full_name='User.recentActiveTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=532,
)


_NETWORKDISCOVERYPACKET = _descriptor.Descriptor(
  name='NetworkDiscoveryPacket',
  full_name='NetworkDiscoveryPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='NetworkDiscoveryPacket.mode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='NetworkDiscoveryPacket.sender', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='groupTag', full_name='NetworkDiscoveryPacket.groupTag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='NetworkDiscoveryPacket.nodeId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeAddress', full_name='NetworkDiscoveryPacket.nodeAddress', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodePort', full_name='NetworkDiscoveryPacket.nodePort', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret', full_name='NetworkDiscoveryPacket.secret', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NETWORKDISCOVERYPACKET_SENDER,
    _NETWORKDISCOVERYPACKET_MODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=888,
)

_ROUTE1.fields_by_name['path'].enum_type = _ROUTE1_PATH
_ROUTE1.fields_by_name['networkDiscoveryPacket'].message_type = _NETWORKDISCOVERYPACKET
_ROUTE1.fields_by_name['user'].message_type = _USER
_ROUTE1.fields_by_name['message'].message_type = _MESSAGE
_ROUTE1_PATH.containing_type = _ROUTE1
_ROUTE1.oneofs_by_name['payload'].fields.append(
  _ROUTE1.fields_by_name['networkDiscoveryPacket'])
_ROUTE1.fields_by_name['networkDiscoveryPacket'].containing_oneof = _ROUTE1.oneofs_by_name['payload']
_ROUTE1.oneofs_by_name['payload'].fields.append(
  _ROUTE1.fields_by_name['user'])
_ROUTE1.fields_by_name['user'].containing_oneof = _ROUTE1.oneofs_by_name['payload']
_ROUTE1.oneofs_by_name['payload'].fields.append(
  _ROUTE1.fields_by_name['message'])
_ROUTE1.fields_by_name['message'].containing_oneof = _ROUTE1.oneofs_by_name['payload']
_MESSAGE.fields_by_name['type'].enum_type = _MESSAGE_TYPE
_MESSAGE.fields_by_name['status'].enum_type = _MESSAGE_STATUS
_MESSAGE_TYPE.containing_type = _MESSAGE
_MESSAGE_STATUS.containing_type = _MESSAGE
_NETWORKDISCOVERYPACKET.fields_by_name['mode'].enum_type = _NETWORKDISCOVERYPACKET_MODE
_NETWORKDISCOVERYPACKET.fields_by_name['sender'].enum_type = _NETWORKDISCOVERYPACKET_SENDER
_NETWORKDISCOVERYPACKET_SENDER.containing_type = _NETWORKDISCOVERYPACKET
_NETWORKDISCOVERYPACKET_MODE.containing_type = _NETWORKDISCOVERYPACKET
DESCRIPTOR.message_types_by_name['Route1'] = _ROUTE1
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['NetworkDiscoveryPacket'] = _NETWORKDISCOVERYPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Route1 = _reflection.GeneratedProtocolMessageType('Route1', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE1,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:Route1)
  ))
_sym_db.RegisterMessage(Route1)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:User)
  ))
_sym_db.RegisterMessage(User)

NetworkDiscoveryPacket = _reflection.GeneratedProtocolMessageType('NetworkDiscoveryPacket', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKDISCOVERYPACKET,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:NetworkDiscoveryPacket)
  ))
_sym_db.RegisterMessage(NetworkDiscoveryPacket)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007routingH\001'))
# @@protoc_insertion_point(module_scope)
